
version: 2
project_name: PigeonHole Cli
# dockers:
# - dockerfile: Dockerfile
  # id: pigeonhole-cli
  # # binaries:
  # # - pigeonhole-cli
  # # goos: linux
  # # goarch: amd64
  # # goarm: ''
  # # goamd64: 'v2'
  # skip_push: true
  # image_templates:
  #   - "pigeonholeio/pigeonhole-cli:latest"
# sboms:
#   - artifacts: binary
    # documents:
    #   - "${artifact}.spdx.sbom"
# archives:
#   - format: gz
#     files:
#       - none*
archives:
  - format: tar.gz
# signs:
#   - artifacts: all
report_sizes: false
metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"
builds:
  - id: default
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    no_unique_dist_dir: true
    dir: src
    main: .
    binary: "pigeonhole-cli/{{ .Version }}/{{ .Os }}/{{ .Arch }}/pigeonhole-cli"
    # binary: pigeonhole
    builder: go
    gobinary: go
    command: build
    ldflags:
      - -X github.com/pigeonholeio/pigeonhole-cli/cmd.Version={{.Version}}
      - -X github.com/pigeonholeio/pigeonhole-cli/cmd.CommitHash={{.ShortCommit}}
      - -X github.com/pigeonholeio/pigeonhole-cli/cmd.BuildTime={{.Date}}
      - -X github.com/pigeonholeio/pigeonhole-cli/cmd.BuiltBy=goreleaser
    env:
      - CGO_ENABLED=0


brews:
  - name: pigeonhole-cli

    repository:
      # Repository owner template. (templateable)
      owner: pigeonholeio
      # Repository name. (templateable)
      name: homebrew-pigeonhole
      # Optionally a branch can be provided. (templateable)
      #
      # Defaults to the default repository branch.
      branch: main
      git:
        private_key: /Users/server/.ssh/id_rsa



checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
  algorithm: sha256

# source:
#   name_template: '{{ .ProjectName }}-{{ .Version }}'
#   format: tar.gz
gomod:
  gobinary: go

changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^updaated'

release:
  github:
    owner: pigeonholeio
    name: pigeonhole-cli
  name_template: "{{.ProjectName}} v{{.Version}}"

  draft: false
  # replace_existing_draft: false
  # replace_existing_artifacts: true
  # use_existing_draft: true
  mode: replace
  header: |
    # 🚀 A new PigeonHole CLI release
    You can find the binaries at [https://releases.pigeono.io](https://releases.pigeono.io)

  footer: |
    ## Thanks

    Those were the changes on {{ .Tag }}!
    Don't forget if you like the tool and would like to help, there are several ways you can [help the project](https://pigeono.io/about/getinvolved/)
    

  skip_upload: true


  disable: false
