
version: 2
project_name: PigeonHole Cli
# dockers:
# - dockerfile: Dockerfile
  # id: pigeonhole-cli
  # # binaries:
  # # - pigeonhole-cli
  # # goos: linux
  # # goarch: amd64
  # # goarm: ''
  # # goamd64: 'v2'
  # skip_push: true
  # image_templates:
  #   - "pigeonholeio/pigeonhole-cli:latest"
# sboms:
#   - artifacts: binary
    # documents:
    #   - "${artifact}.spdx.sbom"
# archives:
#   - format: gz
#     files:
#       - none*
archives:

  - name_template: "pigeonhole-cli/{{ .Version }}/{{ .Os }}/{{ .Arch }}/pigeonhole"
    # files:
    #   - none*

# - format: binary
#   name_template: pigeonhole
#   wrap_in_directory: false
  # format_overrides:
  # - # Which GOOS to override the format for.
  #   goos: windows

  #   # The format to use for the given GOOS.
  #   # Valid options are `tar.gz`, `tgz`, `tar.xz`, `txz`, tar`, `gz`, `zip`, `binary`, and `none`.
  #   format: zip
# signs:
#   - artifacts: all
report_sizes: false
metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"
builds:
  - id: default
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    no_unique_dist_dir: true
    dir: src
    main: .
    binary: "pigeonhole-cli/{{ .Version }}/{{ .Os }}/{{ .Arch }}/pigeonhole"
    # binary: pigeonhole
    builder: go
    gobinary: go
    command: build
    ldflags:
      - -X github.com/pigeonholeio/pigeonhole-cli/cmd.Version={{.Version}}
      - -X github.com/pigeonholeio/pigeonhole-cli/cmd.CommitHash={{.ShortCommit}}
      - -X github.com/pigeonholeio/pigeonhole-cli/cmd.BuildTime={{.Date}}
      - -X github.com/pigeonholeio/pigeonhole-cli/cmd.BuiltBy=goreleaser
    env:
      - CGO_ENABLED=0


dockers:
- image_templates:
  - pigeonholeio/pigeonhole-cli:latest-amd64
  - pigeonholeio/pigeonhole-cli:{{ .Version }}-amd64
  - pigeonholeio/pigeonhole-cli:{{ .Major }}-amd64
  - pigeonholeio/pigeonhole-cli:{{ .Major }}.{{ .Minor }}-amd64
  use: buildx
  build_flag_templates:
    - "--pull"
    - "--label=io.pigeono.cli.created={{.Date}}"
    - "--label=io.pigeono.cli.title={{.ProjectName}}"
    - "--label=io.pigeono.cli.revision={{.FullCommit}}"
    - "--label=io.pigeono.cli.version={{.Version}}"
    - "--platform=linux/amd64"
- image_templates:
  - pigeonholeio/pigeonhole-cli:latest-arm64
  - pigeonholeio/pigeonhole-cli:{{ .Version }}-arm64
  - pigeonholeio/pigeonhole-cli:{{ .Major }}-arm64
  - pigeonholeio/pigeonhole-cli:{{ .Major }}.{{ .Minor }}-arm64
  use: buildx
  dockerfile: Dockerfile
  build_flag_templates:
    - "--pull"
    - "--label=io.pigeono.cli.created={{.Date}}"
    - "--label=io.pigeono.cli.title={{.ProjectName}}"
    - "--label=io.pigeono.cli.revision={{.FullCommit}}"
    - "--label=io.pigeono.cli.version={{.Version}}"
    - "--platform=linux/arm64"
  goarch: arm64

docker_manifests:
- name_template: "pigeonholeio/pigeonhole-cli:latest"
  image_templates:
    - "pigeonholeio/pigeonhole-cli:latest-amd64"
    - "pigeonholeio/pigeonhole-cli:latest-arm64"
- name_template: "pigeonholeio/pigeonhole-cli:{{ .Version }}"
  image_templates:
    - "pigeonholeio/pigeonhole-cli:{{ .Version }}-amd64"
    - "pigeonholeio/pigeonhole-cli:{{ .Version }}-arm64"
- name_template: "pigeonholeio/pigeonhole-cli:{{ .Major }}"
  image_templates:
    - "pigeonholeio/pigeonhole-cli:{{ .Major }}-amd64"
    - "pigeonholeio/pigeonhole-cli:{{ .Major }}-arm64"
- name_template: "pigeonholeio/pigeonhole-cli:{{ .Major }}.{{ .Minor }}"
  image_templates:
    - "pigeonholeio/pigeonhole-cli:{{ .Major }}.{{ .Minor }}-amd64"
    - "pigeonholeio/pigeonhole-cli:{{ .Major }}.{{ .Minor }}-arm64"

brews:
  - name: pigeonhole-cli
    repository:
      owner: pigeonholeio
      name: homebrew-pigeonhole
      branch: main
      git:
        private_key: /Users/server/.ssh/id_rsa
    url_template: https://releases.pigeono.io/{{ .Version }}/{{ .Os }}/{{ .Arch }}/pigeonhole.tar.gz
    homepage: https://pigeono.io
    description: "Sending your secrets securely!"
    install: |
      bin.install "{{ .Version }}/{{ .Os }}/{{ .Arch }}/pigeonhole"
    # skip_upload: false
# blobs:
#   # You can have multiple blob configs
#   - provider: s3
#     region: eu-west-2
#     bucket: releases.pigeono.io
#     ids:
#     - default
#     include_meta: false
#     directory: "pigeonhole-cli"
#     # directory: "pigeonhole-cli/{{ .Version }}/{{ .Os }}/{{ .Arch }}"
    



# winget:
#   - # Name of the recipe
#     #
#     # Default: the project name.
#     # Templates: allowed.
#     name: pigeonhole-cli

#     # Publisher name.
#     #
#     # Templates: allowed.
#     # Required
#     publisher: PigeonHole

#     # Your app's description.
#     #
#     # Templates: allowed.
#     # Required
#     # Default: inferred from global metadata.
#     short_description: "Software to create fast and easy drum rolls."



checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
  algorithm: sha256

# source:
#   name_template: '{{ .ProjectName }}-{{ .Version }}'
#   format: tar.gz
gomod:
  gobinary: go

changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^updaated'

release:
  github:
    owner: pigeonholeio
    name: pigeonhole-cli
  name_template: "{{.ProjectName}} v{{.Version}}"

  draft: false
  # replace_existing_draft: false
  # replace_existing_artifacts: true
  # use_existing_draft: true
  mode: replace
  header: |
    # 🚀 A new PigeonHole CLI release
    You can find the binaries at [https://releases.pigeono.io](https://releases.pigeono.io)

  footer: |
    ## Thanks for supporting,

    Those were the changes on {{ .Tag }}!
    Don't forget if you like the tool and would like to help, there are several ways you can [help the project](https://pigeono.io/about/getinvolved/)
    

  skip_upload: true


  disable: false
