// Package sdk provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package sdk

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	Jwt_azureScopes      = "jwt_azure.Scopes"
	Jwt_pigeonholeScopes = "jwt_pigeonhole.Scopes"
)

// CreateSecret defines model for CreateSecret.
type CreateSecret struct {
	// RecipientIds A list of recipient IDs.
	RecipientIds []string `json:"recipient_ids"`

	// Reference A reference string for the secret.
	Reference string `json:"reference"`
}

// CreateSecretResponse defines model for CreateSecretResponse.
type CreateSecretResponse struct {
	S3Info *struct {
		Fields *struct {
			Key                  *string   `json:"key,omitempty"`
			Policy               *string   `json:"policy,omitempty"`
			XAmzAlgorithm        *string   `json:"x-amz-algorithm,omitempty"`
			XAmzCredential       *string   `json:"x-amz-credential,omitempty"`
			XAmzDate             *string   `json:"x-amz-date,omitempty"`
			XAmzMetaRecipientIds *[]string `json:"x-amz-meta-recipient_ids,omitempty"`
			XAmzMetaReference    *string   `json:"x-amz-meta-reference,omitempty"`
			XAmzMetaSenderId     *string   `json:"x-amz-meta-sender_id,omitempty"`
			XAmzSignature        *string   `json:"x-amz-signature,omitempty"`
		} `json:"fields,omitempty"`
		Url *string `json:"url,omitempty"`
	} `json:"s3_info,omitempty"`
	Users *[]User `json:"users,omitempty"`
}

// GeneralErrorResponse defines model for GeneralErrorResponse.
type GeneralErrorResponse struct {
	Message string `json:"message"`
}

// Key defines model for Key.
type Key struct {
	CreatedAt *time.Time          `json:"created_at,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`
	KeyData   *string             `json:"key_data,omitempty"`
	Reference *string             `json:"reference,omitempty"`
}

// NewKey defines model for NewKey.
type NewKey struct {
	Force     *bool   `json:"force,omitempty"`
	KeyData   *string `json:"key_data,omitempty"`
	Only      *bool   `json:"only,omitempty"`
	Reference *string `json:"reference,omitempty"`
	Thumbprint *string `json:"thumbprint,omitempty"`
}

// Secret defines model for Secret.
type Secret struct {
	Id        *openapi_types.UUID `json:"id,omitempty"`
	Recipient *string             `json:"recipient,omitempty"`
	Reference *string             `json:"reference,omitempty"`
	Sender    *string             `json:"sender,omitempty"`
}

// Token defines model for Token.
type Token struct {
	AccessToken string `json:"accessToken"`
}

// User defines model for User.
type User struct {
	Email     *string             `json:"email,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`
	Keys      *[]Key              `json:"keys,omitempty"`
	Shortcode *string             `json:"shortcode,omitempty"`
}

// Keys defines model for Keys.
type Keys = []Key

// Secrets defines model for Secrets.
type Secrets = []Secret

// Users defines model for Users.
type Users = []User

// SecretGetParams defines parameters for SecretGet.
type SecretGetParams struct {
	Reference *string `form:"reference,omitempty" json:"reference,omitempty"`
}

// UserGetParams defines parameters for UserGet.
type UserGetParams struct {
	Id *[]string `form:"id,omitempty" json:"id,omitempty"`
}

// SecretPostJSONRequestBody defines body for SecretPost for application/json ContentType.
type SecretPostJSONRequestBody = CreateSecret

// UserMeKeyPostJSONRequestBody defines body for UserMeKeyPost for application/json ContentType.
type UserMeKeyPostJSONRequestBody = NewKey

// UserIdKeyPostJSONRequestBody defines body for UserIdKeyPost for application/json ContentType.
type UserIdKeyPostJSONRequestBody = NewKey

// UserIdKeyIdDeleteJSONRequestBody defines body for UserIdKeyIdDelete for application/json ContentType.
type UserIdKeyIdDeleteJSONRequestBody = Key

// UserIdKeyIdGetJSONRequestBody defines body for UserIdKeyIdGet for application/json ContentType.
type UserIdKeyIdGetJSONRequestBody = Key
