

update-go:
	go get -u
	go mod tidy 
	go mod vendor


post-secret-test:
	go run main.go s s -r rhys@rhysevans.co.uk -f ./vendor
	go run main.go s s -r rhys@rhysevans.co.uk -f ./vendor
	go run main.go s s -r rhys@rhysevans.co.uk -f ./vendor
	go run main.go s s -r rhys@rhysevans.co.uk -f ./vendor
	go run main.go s s -r rhys@rhysevans.co.uk -f ./vendor
	go run main.go s s -r rhys@rhysevans.co.uk -f ./vendor
	go run main.go s s -r rhys@rhysevans.co.uk -f ./vendor
	go run main.go s s -r rhys@rhysevans.co.uk -f ./vendor
	go run main.go s s -r rhys@rhysevans.co.uk -f ./vendor
	go run main.go s s -r rhys@rhysevans.co.uk -f ./vendor
	go run main.go s s -r rhys@rhysevans.co.uk -f ./vendor
	go run main.go s s -r rhys@rhysevans.co.uk -f ./vendor
	go run main.go s s -r rhys@rhysevans.co.uk -f ./vendor